version : '2.2'

services:
  app:
    build: .  
    # ports:
    #   - "8080:8080"
    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - MYSQLDB_VOLUME:/var/lib/mysql
      - ./mysql-dump.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
    networks:
      - backend
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 12s
      timeout: 180s
      retries: 220
  nginx:
    image: nginx:1.21-alpine
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
      -  ./src/main/webapp:/etc/nginx/html/static
    depends_on:
         - app
    ports:
      - 80:80
    networks:
      - frontend
   




volumes:
  MYSQLDB_VOLUME:
    driver: local  
networks:
  backend:
  frontend:

      