version : '2.2'

services:
  lavagna:
    build: .
    image : 558924459154.dkr.ecr.eu-central-1.amazonaws.com/dev_lava


    networks:
      - backend
      - frontend
    depends_on:
      mysql:
        condition: service_healthy  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - MYSQLDB_VOLUME:/var/lib/mysql
      - ./mysql-dump.sql:/docker-entrypoint-initdb.d/mysql-dump.sql
    networks:
      - backend
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 12s
      timeout: 180s
      retries: 220
  nginx:
    image: nginx:1.21-alpine
    volumes:
      -  ./nginx.conf:/etc/nginx/nginx.conf
      -  ./src/main/webapp/:/usr/share/nginx/static/
      - ./target/lavagna/help/:/usr/share/nginx/doc/html # #i add to line 473 in the pom file hostname : 0.0.0.0 so dont need to mount 
    depends_on:
         - lavagna
    ports:
      - 80:80
      - 8081:8081
    networks:
      - frontend

  doc:

    build: 
    context: .
      dockerfile: doc.Dockerfile
    volumes:
       - $PWD/target:/doc/target/   #i add to line 473 in the pom file hostname : 0.0.0.0 so dont need the volume 
    networks:
       - frontend 

volumes:
  MYSQLDB_VOLUME:
    driver: local  
networks:
  backend:
  frontend:
      
